### PR TITLE
DM-34986: build with pyproject.toml

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by wvreeven — APPROVED** [review]
Looks good to me.

**Comment by r-owen** [comment]
I redid the entry point code. I also discovered I had put the Jenkinsfile in the wrong place (I found it in doc/).

**Comment by r-owen** [comment]
I redid the entry point code and move Jenkinsfile from doc/ up a level.

**Review by wvreeven — APPROVED** [review]
Looks good to me.

**Pull request merged**
